import { describe, expect, test } from "bun:test";
import {
  bumpFromCommits,
  extractChangelogSection,
  isIgnoredCommit,
  latestVersionTag,
  lintCommitMessage,
  lintPrTitle,
  nextVersion,
  parseCommit,
  prependChangelog,
  renderReleaseNotes,
} from "../scripts/conventional.mjs";

describe("parseCommit", () => {
  test("parses a typed subject with optional scope", () => {
    expect(parseCommit("feat: add per-site pause")).toMatchObject({
      type: "feat",
      scope: null,
      breaking: false,
      description: "add per-site pause",
    });
    expect(parseCommit("fix(popup): restore contrast")).toMatchObject({
      type: "fix",
      scope: "popup",
      description: "restore contrast",
    });
  });

  test("detects breaking changes from ! and footer", () => {
    expect(parseCommit("feat!: rename storage keys").breaking).toBe(true);
    expect(
      parseCommit("feat: rename keys\n\nBREAKING CHANGE: storage keys changed").breaking,
    ).toBe(true);
    expect(
      parseCommit("fix: typo\n\nBREAKING-CHANGE: behavior changed").breaking,
    ).toBe(true);
  });

  test("returns null for non-conventional messages", () => {
    expect(parseCommit("Add a feature")).toBeNull();
    expect(parseCommit("feat add thing")).toBeNull();
    expect(parseCommit("FEAT: shout")).toBeNull();
  });
});

describe("isIgnoredCommit", () => {
  test("ignores merges and release chores", () => {
    expect(isIgnoredCommit("Merge pull request #3 from yannelli/switch-npm-to-bun")).toBe(true);
    expect(isIgnoredCommit("chore(release): 0.2.0 [skip ci]")).toBe(true);
    expect(isIgnoredCommit("feat: add pause")).toBe(false);
  });
});

describe("bumpFromCommits", () => {
  test("maps conventional types to semver bumps", () => {
    expect(bumpFromCommits(["feat: add pause"])).toBe("minor");
    expect(bumpFromCommits(["fix: contrast"])).toBe("patch");
    expect(bumpFromCommits(["perf: skip unused observers"])).toBe("patch");
    expect(bumpFromCommits(["feat!: rename keys"])).toBe("major");
    expect(bumpFromCommits(["chore: tidy", "docs: readme"])).toBeNull();
  });

  test("uses the highest bump and skips ignored commits", () => {
    expect(
      bumpFromCommits([
        "Merge pull request #1 from yannelli/x",
        "fix: typo",
        "feat: add pause",
        "chore(release): 0.1.0 [skip ci]",
      ]),
    ).toBe("minor");
  });
});

describe("nextVersion", () => {
  test("bumps semver and rejects prerelease output", () => {
    expect(nextVersion("0.1.0", "patch")).toBe("0.1.1");
    expect(nextVersion("0.1.0", "minor")).toBe("0.2.0");
    expect(nextVersion("0.1.0", "major")).toBe("1.0.0");
    expect(nextVersion("1.4.2", "minor")).toBe("1.5.0");
  });
});

describe("latestVersionTag", () => {
  test("returns the highest vX.Y.Z tag", () => {
    expect(latestVersionTag(["v0.1.0", "v0.2.0", "nightly"])).toBe("v0.2.0");
    expect(latestVersionTag([])).toBeNull();
  });
});

describe("lintCommitMessage and lintPrTitle", () => {
  test("accepts conventional subjects and PR titles with a pull number", () => {
    expect(lintCommitMessage("feat: add pause").ok).toBe(true);
    expect(lintCommitMessage("feat: add pause\n\nDetails here.").ok).toBe(true);
    expect(lintPrTitle("fix(popup): restore contrast (#4)").ok).toBe(true);
    expect(lintPrTitle("Revert \"feat: add pause\"").ok).toBe(true);
  });

  test("rejects free-form titles", () => {
    expect(lintPrTitle("Fixed the popup").ok).toBe(false);
    expect(lintCommitMessage("updated stuff").ok).toBe(false);
  });
});

describe("changelog", () => {
  test("renders Keep a Changelog notes without authors or generators", () => {
    const notes = renderReleaseNotes({
      version: "0.2.0",
      date: "2026-08-27",
      commits: [
        { type: "feat", description: "add per-site pause (#1)", author: "github-actions[bot]" },
        { type: "fix", description: "restore contrast" },
      ],
    });

    expect(notes).toContain("## [0.2.0] - 2026-08-27");
    expect(notes).toContain("### Added");
    expect(notes).toContain("add per-site pause (#1)");
    expect(notes).toContain("### Fixed");
    expect(notes).not.toMatch(/generated by/i);
    expect(notes).not.toMatch(/co-authored-by/i);
    expect(notes).not.toContain("github-actions");
    expect(notes).not.toMatch(/\[bot\]/i);
    expect(notes).not.toMatch(/semantic-release/i);
  });

  test("prepends a release section under the changelog header", () => {
    const existing = `# Changelog

All notable changes to this project are documented in this file.

## [0.1.0] - 2026-08-27

### Added

- Initial extension
`;
    const next = renderReleaseNotes({
      version: "0.2.0",
      date: "2026-08-27",
      commits: [{ type: "feat", description: "add cursor blocker" }],
    });
    const combined = prependChangelog(existing, next);
    expect(combined.indexOf("## [0.2.0]")).toBeLessThan(combined.indexOf("## [0.1.0]"));
    expect(extractChangelogSection(combined, "0.1.0")).toContain("Initial extension");
  });
});
