import { describe, expect, test } from "bun:test";
import { mkdtempSync, readFileSync, writeFileSync } from "node:fs";
import { tmpdir } from "node:os";
import { join } from "node:path";
import { applyRelease, assertHumanActor, planRelease } from "../scripts/release.mjs";

describe("assertHumanActor", () => {
  test("allows a person and refuses bot identities", () => {
    expect(() =>
      assertHumanActor({ login: "yannelli", type: "User", name: "Ryan Yannelli" }),
    ).not.toThrow();
    expect(() => assertHumanActor({ login: "github-actions[bot]", type: "Bot" })).toThrow(/bot/i);
    expect(() => assertHumanActor({ login: "semantic-release-bot", type: "User" })).toThrow(/bot/i);
    expect(() => assertHumanActor(null)).toThrow(/token/i);
  });
});

describe("planRelease", () => {
  test("bootstraps the current version when there are no tags or releasable commits", () => {
    expect(
      planRelease({
        currentVersion: "0.1.0",
        tags: [],
        commits: ["ci: add contributing guidelines", "Merge pull request #3 from x"],
      }),
    ).toEqual({ action: "bootstrap", version: "0.1.0" });
  });

  test("skips when the latest tag already covers non-releasable commits", () => {
    expect(
      planRelease({
        currentVersion: "0.1.0",
        tags: ["v0.1.0"],
        commits: ["docs: tweak readme", "chore: tidy"],
      }),
    ).toEqual({ action: "skip" });
  });

  test("plans a semver release from conventional commits", () => {
    const plan = planRelease({
      currentVersion: "0.1.0",
      tags: ["v0.1.0"],
      commits: ["feat: add cursor blocker", "fix: contrast"],
      date: "2026-08-27",
    });
    expect(plan.action).toBe("release");
    expect(plan.version).toBe("0.2.0");
    expect(plan.bump).toBe("minor");
    expect(plan.notes).toContain("## [0.2.0] - 2026-08-27");
    expect(plan.notes).not.toMatch(/generated by/i);
  });
});

describe("applyRelease", () => {
  test("bumps versions and prepends changelog notes without attribution", () => {
    const root = mkdtempSync(join(tmpdir(), "im-an-adult-release-"));
    writeFileSync(join(root, "package.json"), `${JSON.stringify({ name: "im-an-adult", version: "0.1.0" }, null, 2)}\n`);
    writeFileSync(
      join(root, "manifest.json"),
      `${JSON.stringify({ manifest_version: 3, name: "I'm an Adult", version: "0.1.0" }, null, 2)}\n`,
    );
    writeFileSync(
      join(root, "CHANGELOG.md"),
      `# Changelog\n\nAll notable changes to this project are documented in this file.\n\n## [0.1.0] - 2026-08-27\n\n### Added\n\n- Initial extension\n`,
    );

    const notes = "## [0.2.0] - 2026-08-27\n\n### Added\n\n- add cursor blocker\n";
    applyRelease({ root, version: "0.2.0", notes, packageZip: false });

    const pkg = JSON.parse(readFileSync(join(root, "package.json"), "utf8"));
    const manifest = JSON.parse(readFileSync(join(root, "manifest.json"), "utf8"));
    const changelog = readFileSync(join(root, "CHANGELOG.md"), "utf8");
    expect(pkg.version).toBe("0.2.0");
    expect(manifest.version).toBe("0.2.0");
    expect(changelog).toContain("## [0.2.0] - 2026-08-27");
    expect(changelog).toContain("## [0.1.0] - 2026-08-27");
    expect(changelog).not.toMatch(/co-authored-by/i);
    expect(changelog).not.toMatch(/\[bot\]/i);
  });
});
